version: '3'

services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  userCrud:
    build:
      context: .
      dockerfile: Dockerfile
      enviroment:
        - REPOSITORY_DATABASE=${REPOSITORY_DATABASE}
        - DATABASE_NAME=${DATABASE_NAME}
        - USERS_TABLE_OR_COLLECTION_NAME=${USERS_TABLE_OR_COLLECTION_NAME}
        - DATABASE_URI=${DATABASE_URI}
      ports:
        - '3000:3000'
      networks:
        - app-network
      links:
        - mongodb
networks:
  app-network:
    driver: bridge